/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard.payouts'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSlotsRouteImport } from './routes/dashboard.slots'
import { Route as DashboardBookingsIndexRouteImport } from './routes/dashboard.bookings.index'
import { Route as DashboardBookingsBookingIdRouteImport } from './routes/dashboard.bookings.$bookingId'
import { Route as DashboardPayoutsIndexRouteImport } from './routes/dashboard.payouts.index'
import { Route as DashboardPayoutsHistoryRouteImport } from './routes/dashboard.payouts.history'
import { Route as DashboardPayoutsSettingsRouteImport } from './routes/dashboard.payouts.settings'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as DashboardSettingsAccountRouteImport } from './routes/dashboard.settings.account'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard.settings.notifications'
import { Route as DashboardSettingsStaffRouteImport } from './routes/dashboard.settings.staff'
import { Route as DashboardSlotsIndexRouteImport } from './routes/dashboard.slots.index'
import { Route as DashboardSlotsCourtsRouteImport } from './routes/dashboard.slots.courts'
import { Route as DashboardSlotsSetupRouteImport } from './routes/dashboard.slots.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSlotsRoute = DashboardSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsIndexRoute = DashboardBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const DashboardBookingsBookingIdRoute =
  DashboardBookingsBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => DashboardBookingsRoute,
  } as any)
const DashboardPayoutsIndexRoute = DashboardPayoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPayoutsRoute,
} as any)
const DashboardPayoutsHistoryRoute = DashboardPayoutsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardPayoutsRoute,
} as any)
const DashboardPayoutsSettingsRoute =
  DashboardPayoutsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardPayoutsRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsStaffRoute = DashboardSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSlotsIndexRoute = DashboardSlotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSlotsRoute,
} as any)
const DashboardSlotsCourtsRoute = DashboardSlotsCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => DashboardSlotsRoute,
} as any)
const DashboardSlotsSetupRoute = DashboardSlotsSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardSlotsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pending': typeof PendingRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/payouts': typeof DashboardPayoutsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/slots': typeof DashboardSlotsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/dashboard/payouts/history': typeof DashboardPayoutsHistoryRoute
  '/dashboard/payouts/settings': typeof DashboardPayoutsSettingsRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/staff': typeof DashboardSettingsStaffRoute
  '/dashboard/slots/courts': typeof DashboardSlotsCourtsRoute
  '/dashboard/slots/setup': typeof DashboardSlotsSetupRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/dashboard/payouts/': typeof DashboardPayoutsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/slots/': typeof DashboardSlotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pending': typeof PendingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/dashboard/payouts/history': typeof DashboardPayoutsHistoryRoute
  '/dashboard/payouts/settings': typeof DashboardPayoutsSettingsRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/staff': typeof DashboardSettingsStaffRoute
  '/dashboard/slots/courts': typeof DashboardSlotsCourtsRoute
  '/dashboard/slots/setup': typeof DashboardSlotsSetupRoute
  '/dashboard/bookings': typeof DashboardBookingsIndexRoute
  '/dashboard/payouts': typeof DashboardPayoutsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/slots': typeof DashboardSlotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pending': typeof PendingRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/payouts': typeof DashboardPayoutsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/slots': typeof DashboardSlotsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/dashboard/payouts/history': typeof DashboardPayoutsHistoryRoute
  '/dashboard/payouts/settings': typeof DashboardPayoutsSettingsRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/staff': typeof DashboardSettingsStaffRoute
  '/dashboard/slots/courts': typeof DashboardSlotsCourtsRoute
  '/dashboard/slots/setup': typeof DashboardSlotsSetupRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/dashboard/payouts/': typeof DashboardPayoutsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/slots/': typeof DashboardSlotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pending'
    | '/dashboard/bookings'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/slots'
    | '/dashboard/'
    | '/dashboard/bookings/$bookingId'
    | '/dashboard/payouts/history'
    | '/dashboard/payouts/settings'
    | '/dashboard/settings/account'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/staff'
    | '/dashboard/slots/courts'
    | '/dashboard/slots/setup'
    | '/dashboard/bookings/'
    | '/dashboard/payouts/'
    | '/dashboard/settings/'
    | '/dashboard/slots/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pending'
    | '/dashboard'
    | '/dashboard/bookings/$bookingId'
    | '/dashboard/payouts/history'
    | '/dashboard/payouts/settings'
    | '/dashboard/settings/account'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/staff'
    | '/dashboard/slots/courts'
    | '/dashboard/slots/setup'
    | '/dashboard/bookings'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/slots'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pending'
    | '/dashboard/bookings'
    | '/dashboard/payouts'
    | '/dashboard/settings'
    | '/dashboard/slots'
    | '/dashboard/'
    | '/dashboard/bookings/$bookingId'
    | '/dashboard/payouts/history'
    | '/dashboard/payouts/settings'
    | '/dashboard/settings/account'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/staff'
    | '/dashboard/slots/courts'
    | '/dashboard/slots/setup'
    | '/dashboard/bookings/'
    | '/dashboard/payouts/'
    | '/dashboard/settings/'
    | '/dashboard/slots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PendingRoute: typeof PendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/slots': {
      id: '/dashboard/slots'
      path: '/slots'
      fullPath: '/dashboard/slots'
      preLoaderRoute: typeof DashboardSlotsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings/': {
      id: '/dashboard/bookings/'
      path: '/'
      fullPath: '/dashboard/bookings/'
      preLoaderRoute: typeof DashboardBookingsIndexRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/bookings/$bookingId': {
      id: '/dashboard/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/dashboard/bookings/$bookingId'
      preLoaderRoute: typeof DashboardBookingsBookingIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/payouts/': {
      id: '/dashboard/payouts/'
      path: '/'
      fullPath: '/dashboard/payouts/'
      preLoaderRoute: typeof DashboardPayoutsIndexRouteImport
      parentRoute: typeof DashboardPayoutsRoute
    }
    '/dashboard/payouts/history': {
      id: '/dashboard/payouts/history'
      path: '/history'
      fullPath: '/dashboard/payouts/history'
      preLoaderRoute: typeof DashboardPayoutsHistoryRouteImport
      parentRoute: typeof DashboardPayoutsRoute
    }
    '/dashboard/payouts/settings': {
      id: '/dashboard/payouts/settings'
      path: '/settings'
      fullPath: '/dashboard/payouts/settings'
      preLoaderRoute: typeof DashboardPayoutsSettingsRouteImport
      parentRoute: typeof DashboardPayoutsRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/staff': {
      id: '/dashboard/settings/staff'
      path: '/staff'
      fullPath: '/dashboard/settings/staff'
      preLoaderRoute: typeof DashboardSettingsStaffRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/slots/': {
      id: '/dashboard/slots/'
      path: '/'
      fullPath: '/dashboard/slots/'
      preLoaderRoute: typeof DashboardSlotsIndexRouteImport
      parentRoute: typeof DashboardSlotsRoute
    }
    '/dashboard/slots/courts': {
      id: '/dashboard/slots/courts'
      path: '/courts'
      fullPath: '/dashboard/slots/courts'
      preLoaderRoute: typeof DashboardSlotsCourtsRouteImport
      parentRoute: typeof DashboardSlotsRoute
    }
    '/dashboard/slots/setup': {
      id: '/dashboard/slots/setup'
      path: '/setup'
      fullPath: '/dashboard/slots/setup'
      preLoaderRoute: typeof DashboardSlotsSetupRouteImport
      parentRoute: typeof DashboardSlotsRoute
    }
  }
}

interface DashboardBookingsRouteChildren {
  DashboardBookingsBookingIdRoute: typeof DashboardBookingsBookingIdRoute
  DashboardBookingsIndexRoute: typeof DashboardBookingsIndexRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsBookingIdRoute: DashboardBookingsBookingIdRoute,
  DashboardBookingsIndexRoute: DashboardBookingsIndexRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardPayoutsRouteChildren {
  DashboardPayoutsHistoryRoute: typeof DashboardPayoutsHistoryRoute
  DashboardPayoutsSettingsRoute: typeof DashboardPayoutsSettingsRoute
  DashboardPayoutsIndexRoute: typeof DashboardPayoutsIndexRoute
}

const DashboardPayoutsRouteChildren: DashboardPayoutsRouteChildren = {
  DashboardPayoutsHistoryRoute: DashboardPayoutsHistoryRoute,
  DashboardPayoutsSettingsRoute: DashboardPayoutsSettingsRoute,
  DashboardPayoutsIndexRoute: DashboardPayoutsIndexRoute,
}

const DashboardPayoutsRouteWithChildren =
  DashboardPayoutsRoute._addFileChildren(DashboardPayoutsRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsStaffRoute: typeof DashboardSettingsStaffRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsStaffRoute: DashboardSettingsStaffRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardSlotsRouteChildren {
  DashboardSlotsCourtsRoute: typeof DashboardSlotsCourtsRoute
  DashboardSlotsSetupRoute: typeof DashboardSlotsSetupRoute
  DashboardSlotsIndexRoute: typeof DashboardSlotsIndexRoute
}

const DashboardSlotsRouteChildren: DashboardSlotsRouteChildren = {
  DashboardSlotsCourtsRoute: DashboardSlotsCourtsRoute,
  DashboardSlotsSetupRoute: DashboardSlotsSetupRoute,
  DashboardSlotsIndexRoute: DashboardSlotsIndexRoute,
}

const DashboardSlotsRouteWithChildren = DashboardSlotsRoute._addFileChildren(
  DashboardSlotsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardPayoutsRoute: typeof DashboardPayoutsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardSlotsRoute: typeof DashboardSlotsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardPayoutsRoute: DashboardPayoutsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardSlotsRoute: DashboardSlotsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PendingRoute: PendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
